runtime: python38
service: multisig-wallet

handlers:
  - url: /static
    static_dir: static

  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico

  - url: /manifest.json
    static_files: manifest.json
    upload: manifest.json

  - url: /transaction.js
    static_files: transaction.js
    upload: transaction.js

  - url: /.*
    static_files: index.html
    upload: index.html
